
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry for connecting to the Greengrass MQTT broker (Moquette)
mqtt:
  broker: localhost
  port: 8883
  # CA certificate copied from /greengrass/v2/work/aws.greengrass.clientdevices.Auth/ca.pem
  certificate: /config/certificates/ca.pem
  client_key: /config/certificates/5ea21074803efb854ed5c929cab35fc858d6c294445099c65e4ec2b0df82624b-private.pem.key
  client_cert: /config/certificates/5ea21074803efb854ed5c929cab35fc858d6c294445099c65e4ec2b0df82624b-certificate.pem.crt
  client_id: home-assistant
  tls_insecure: false
  protocol: '3.1.1'
